In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
#upload de arquivo:
arquivo_sobe = '/content/drive/MyDrive/Financeiro/2026/Analises/Matriculas2026 Alunos.xlsx'

In [3]:
alunos_biblioteca = pd.read_excel(arquivo_sobe)#

In [4]:
alunos_biblioteca.head()

,Unnamed: 0,Empresa,Codigo,Nome,Turma,Data Matrícula,Tipo Aluno,Pendência Financeira,Primeira Paga,Curso,...,Situação,Nome Resp. Financeiro,Nascimento,Ano de Entrada,Etapa Rematrícula,Bolsa CCT,Bolsa DC,E-mail Resp. Financeiro,E-mail Resp. Residência,Sexo do Aluno
0,1,IEBURIX ALOISE,29064,ABDUL RAHMAN HAFEZ,EM 1A 2026,04/12/2025,Novo,Mensalidade - Ref: Janeiro/2026\rMensalidade -...,Pago,Ensino Médio,...,MT,ULA ABOUL CHAER,18/09/2010,2026,NaN,NaN,DC 40.00% Parcela de 01 a 12,Oulaaboshaer@gmail.com,Oulaaboshaer@gmail.com,M
1,3,IEBURIX ALOISE,28780,AHLAM AHMAD MAZLOUM,EM 3A 2026,18/09/2025,Antigo,NaN,Pago,Ensino Médio,...,MT,ARMANDO OSMAN MAZLOUM,26/05/2009,2024,NaN,NaN,DC 45.00% Parcela de 01 a 12,islamfoz@hotmail.com,zeynabbintmohamad@hotmail.com,F
2,4,IEBURIX ALOISE,28913,ALANIS VITTI MARQUEZIN,EFAI 2ºB 2026,22/09/2025,Antigo,NaN,Pago,Ensino Fundamental,...,MT,LUIS CARLOS MARQUEZIN JUNIOR,16/01/2019,2025,NaN,NaN,DC 26.00% Parcela de 01 a 12,lc.marquezin@hotmail.com,mivitti@hotmail.com,F
3,5,IEBURIX ALOISE,75976,ALICE BRAGA BALDIN,EFAI 4ºA 2026,03/09/2025,Antigo,NaN,Pago,Ensino Fundamental,...,MT,FABRICIO FERREIRA BALDIN,20/01/2017,2023,NaN,NaN,DC 30.00% Parcela de 01 a 12,fbaldinpf2810@gmail.com,patbbaldin@gmail.com,F
4,7,IEBURIX ALOISE,10766,ALICE CHINAGLIA DE OLIVEIRA,EFAI 5ºB 2026,03/09/2025,Antigo,NaN,Pago,Ensino Fundamental,...,MT,PAULO ROBERTO DE OLIVEIRA,06/05/2016,2022,NaN,NaN,DC 24.96% Parcela de 01 a 12,PAULOPRO11@gmail.com,tatichina@gmail.com,F

In [5]:
alunos_biblioteca.columns

Index(['Unnamed: 0', 'Empresa', 'Codigo', 'Nome', 'Turma', 'Data Matrícula',
       'Tipo Aluno', 'Pendência Financeira', 'Primeira Paga', 'Curso', 'Série',
       'Situação', 'Nome Resp. Financeiro', 'Nascimento', 'Ano de Entrada',
       'Etapa Rematrícula', 'Bolsa CCT', 'Bolsa DC', 'E-mail Resp. Financeiro',
       'E-mail Resp. Residência', 'Sexo do Aluno'],
      dtype='object')

In [6]:
# Nome do Aluno,Matrícula Aluno,E-mail Resp. Financeiro,E-mail Resp. Residência,Sexo do Aluno,Data de nascimento,Curso,Série,Turno,Turma
alunos_biblioteca = alunos_biblioteca[['Nome', 'Codigo', 'E-mail Resp. Financeiro', 'Sexo do Aluno', 'Nascimento', 'Curso', 'Série', 'Turma']]

In [7]:
alunos_biblioteca['Turma'].unique()

array(['EM 1A 2026', 'EM 3A 2026', 'EFAI 2ºB 2026', 'EFAI 4ºA 2026',
       'EFAI 5ºB 2026', 'EFAI 4ºB 2026', 'EFAI 1ºA 2026', 'EFAI 3ºA 2026',
       'EFAF 6ºA 2026', 'EFAF 7ºB 2026', 'EFAI 5ºA 2026', 'EFAF 8ºA 2026',
       'EFAI 2ºC 2026', 'Maternal B 2026', 'EFAF 9ºA 2026', 'EM 2A 2026',
       'EFAI 1ºC 2026', 'EFAI 3ºB 2026', 'EFAI 2ºA 2026', 'EFAF 7ºA 2026',
       'EFAI 1ºB 2026', 'EFAF 8ºB 2026', 'Maternal A 2026',
       'Mini Maternal A 2026', 'Mini Maternal B 2026', 'EFAF 9ºB 2026',
       'INTERMEDIÁRIO A 2026', 'Infantil I A 2026', 'Infantil I B 2026',
       'Infantil II B 2026', 'Infantil II A 2026', 'Intermediário B 2026',
       'Berçário B 2026'], dtype=object)

In [8]:
lista_inf_ate_1ano = ['EFAI 1ºA 2026', 'Maternal B 2026', 'EFAI 1ºC 2026',
       'EFAI 1ºB 2026', 'Maternal A 2026', 'Mini Maternal A 2026',
       'Mini Maternal B 2026', 'INTERMEDIÁRIO A 2026',
       'Infantil I A 2026', 'Infantil I B 2026', 'Infantil II B 2026',
       'Infantil II A 2026', 'Intermediário B 2026', 'Berçário B 2026']

In [9]:
alunos_biblioteca_inf_1ano = alunos_biblioteca[alunos_biblioteca['Turma'].isin(lista_inf_ate_1ano)]
alunos_biblioteca_inf_1ano.head()

,Nome,Codigo,E-mail Resp. Financeiro,Sexo do Aluno,Nascimento,Curso,Série,Turma
6,ALICE DE LIMA GIMENES,11735,LINE.LIMA3090@GMAIL.COM,F,08/08/2019,Ensino Fundamental,1º Ano,EFAI 1ºA 2026
15,ALICE SOUZA SANTOS,29035,CSS.SANTOS@ICLOUD.COM,F,24/11/2022,Educação Infantil,Infantil 2,Maternal B 2026
21,AMARILIS LIMA CAVALCANTI SILVA,11781,diego.0411@hotmail.com,F,03/05/2019,Ensino Fundamental,1º Ano,EFAI 1ºC 2026
32,ANNA PORTO DIACOW,11760,LEONARD.DIACOW@GMAIL.COM,F,04/07/2019,Ensino Fundamental,1º Ano,EFAI 1ºC 2026
33,ANNE MONTEIRO MERLINI,11739,MARCELOMERLINI1982@GMAIL.COM,F,30/09/2019,Ensino Fundamental,1º Ano,EFAI 1ºC 2026

In [10]:
alunos_biblioteca_inf_1ano['Turma'].unique()

array(['EFAI 1ºA 2026', 'Maternal B 2026', 'EFAI 1ºC 2026',
       'EFAI 1ºB 2026', 'Maternal A 2026', 'Mini Maternal A 2026',
       'Mini Maternal B 2026', 'INTERMEDIÁRIO A 2026',
       'Infantil I A 2026', 'Infantil I B 2026', 'Infantil II B 2026',
       'Infantil II A 2026', 'Intermediário B 2026', 'Berçário B 2026'],
      dtype=object)

In [11]:
lista_2ano_ate_3em = ['EM 1A 2026', 'EM 3A 2026', 'EFAI 2ºB 2026', 'EFAI 4ºA 2026',
       'EFAI 5ºB 2026', 'EFAI 4ºB 2026', 'EFAI 3ºA 2026', 'EFAF 6ºA 2026',
       'EFAF 7ºB 2026', 'EFAI 5ºA 2026', 'EFAF 8ºA 2026', 'EFAI 2ºC 2026',
       'EFAF 9ºA 2026', 'EM 2A 2026', 'EFAI 3ºB 2026', 'EFAI 2ºA 2026',
       'EFAF 7ºA 2026', 'EFAF 8ºB 2026', 'EFAF 9ºB 2026']

In [12]:
alunos_biblioteca_2ano_3em = alunos_biblioteca[alunos_biblioteca['Turma'].isin(lista_2ano_ate_3em)]
alunos_biblioteca_2ano_3em.head()

,Nome,Codigo,E-mail Resp. Financeiro,Sexo do Aluno,Nascimento,Curso,Série,Turma
0,ABDUL RAHMAN HAFEZ,29064,Oulaaboshaer@gmail.com,M,18/09/2010,Ensino Médio,1º SÉRIE,EM 1A 2026
1,AHLAM AHMAD MAZLOUM,28780,islamfoz@hotmail.com,F,26/05/2009,Ensino Médio,3º SÉRIE,EM 3A 2026
2,ALANIS VITTI MARQUEZIN,28913,lc.marquezin@hotmail.com,F,16/01/2019,Ensino Fundamental,2º Ano,EFAI 2ºB 2026
3,ALICE BRAGA BALDIN,75976,fbaldinpf2810@gmail.com,F,20/01/2017,Ensino Fundamental,4º Ano,EFAI 4ºA 2026
4,ALICE CHINAGLIA DE OLIVEIRA,10766,PAULOPRO11@gmail.com,F,06/05/2016,Ensino Fundamental,5º Ano,EFAI 5ºB 2026

In [13]:
alunos_biblioteca_2ano_3em['Turma'].unique()

array(['EM 1A 2026', 'EM 3A 2026', 'EFAI 2ºB 2026', 'EFAI 4ºA 2026',
       'EFAI 5ºB 2026', 'EFAI 4ºB 2026', 'EFAI 3ºA 2026', 'EFAF 6ºA 2026',
       'EFAF 7ºB 2026', 'EFAI 5ºA 2026', 'EFAF 8ºA 2026', 'EFAI 2ºC 2026',
       'EFAF 9ºA 2026', 'EM 2A 2026', 'EFAI 3ºB 2026', 'EFAI 2ºA 2026',
       'EFAF 7ºA 2026', 'EFAF 8ºB 2026', 'EFAF 9ºB 2026'], dtype=object)

In [14]:
arquivo_salva = '/content/drive/MyDrive/Biblioteca/Importação alunos Sistema Biblioteca/2026/'

In [15]:
#Opção 01 Nao funcionou
'''alunos_biblioteca_inf_1ano.to_csv(arquivo_salva + 'Biblioteca INF - 1ano 2026.csv', index=False, sep=',', encoding='utf-8')
alunos_biblioteca_2ano_3em.to_csv(arquivo_salva + 'Biblioteca 2ano - 3EM 2026.csv', index=False, sep=',', encoding='utf-8')'''

#Opção 02 Nao funcionou
'''# Definindo o caminho (já está no seu notebook, mas garantindo a barra no final)
arquivo_salva = '/content/drive/MyDrive/Biblioteca/Importação alunos Sistema Biblioteca/2026/'

# Salvando o primeiro DataFrame
alunos_biblioteca_inf_1ano.to_csv(arquivo_salva + 'Biblioteca importacao inf ate 1 ano.csv',
    index=False, sep=',', encoding='utf-8', quoting=csv.QUOTE_NONE, escapechar=' '
)

# Salvando o segundo DataFrame
alunos_biblioteca_2ano_3em.to_csv(arquivo_salva + 'Biblioteca importacao2ano ate 3em.csv',
    index=False, sep=',', encoding='utf-8', quoting=csv.QUOTE_NONE, escapechar=' '
)'''


import csv

# Definindo o caminho
arquivo_salva = '/content/drive/MyDrive/Biblioteca/Importação alunos Sistema Biblioteca/2026/'

# Salvando de forma compatível com sistemas antigos
alunos_biblioteca_inf_1ano.to_csv(
    arquivo_salva + 'Biblioteca importacao inf ate 1 ano.csv',
    index=False,
    sep=';',          # Mantendo a vírgula que pediram
    encoding='latin1', # Trocando para o padrão Windows/Brasil
    quoting=1,         # Vamos testar com aspas mínimas primeiro
    quotechar='"'      # Caractere padrão
)

# O mesmo para o segundo
alunos_biblioteca_2ano_3em.to_csv(
    arquivo_salva + 'Biblioteca importacao2ano ate 3em.csv',
    index=False,
    sep=';',
    encoding='latin1',
    quoting=1,
    quotechar='"'
)